print "".isdigit()
print "X".isdigit()
print "XyZ".isdigit()
print "xYz".isdigit()
print "XXX".isdigit()
print "y".isdigit()
print "1A".isdigit()
print "1a".isdigit()
print "^a".isdigit()
print "^A".isdigit()
print "^1".isdigit()
print "1".isdigit()
print "12".isdigit()
print "12.3".isdigit()

