name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  runtests:
    runs-on: ubuntu-latest

    env:
      RAKUDO_VERSION: rakudo-moar-2021.12-01-linux-x86_64-gcc.tar.gz
      RAKUDO_MODULES: Data::Dump App::Prove6

    steps:
      - uses: actions/checkout@v2

      - name: cache rakudo installation
        uses: actions/cache@v2 
        env:
          cache-name: cache-rakudo-deployment
        with:
          path: |
            ~/rakudo
            ~/.rakudo
          key: ${{ env.RAKUDO_VERSION }} ${{ env.RAKUDO_MODULES }}

      - name: setup rakudo environment
        run: |
          set -x
          set -e
          # skip deployment if found
          if [[ -e ~/rakudo ]]; then exit 0; fi;
          wget --quiet -O ~/raku.tar.gz https://rakudo.org/dl/rakudo/${{ env.RAKUDO_VERSION }}
          mkdir ~/rakudo
          tar -xf ~/raku.tar.gz -C ~/rakudo --strip-components=1
          export PATH=~/rakudo/bin:$PATH
          ~/rakudo/share/perl6/site/bin/zef install ${{ env.RAKUDO_MODULES }}

      - name: setup perl environment
        run: |
          mkdir -p ~/perl5lib
          curl -L https://cpanmin.us | perl - -l ~/perl5lib -n Scalar::Util Clone


      - name: Run tests
        run: |
          export PATH=~/rakudo/bin:$PATH
          export PERL5LIB=~/perl5lib/lib/perl5
          ~/rakudo/share/perl6/site/bin/prove6 -v

